services:
  db-pipicucu:
    image: postgres:15
    container_name: db-pipicucu
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pipicucu
      POSTGRES_PORT: 5432
    networks:
      - pipicucu-network
    ports:
      - 8080:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      timeout: 30s
      retries: 5
  api-pipicucu:
    build:
      context: .
    container_name: api-pipicucu
    image: node:24-alpine3.22
    depends_on:
      db-pipicucu:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db-pipicucu
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pipicucu
      - PORT=3001
      - NODE_ENV=production
    networks:
      - pipicucu-network
    volumes:
      - .:/src
    ports:
      - 3001:3001
networks:
  pipicucu-network:
    driver: bridge
