name: 'Backend Workflow'
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pipicucu
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./src
    env:
      POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: checkout node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: install dependencies
        run: npm ci
      - name: run security audit

        run: npm audit --audit-level=high
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./build
